/* 
 *  Setup ATECC608 device 
 */


#include <string.h>  // strlen
#include <stdio.h>   // printf
#include "atca_config.h"
#include "cryptoauthlib.h"
#include "device_cfg.h"

int main(void) {
    char ch;
    ATCA_STATUS status;
    uint8_t text_buffer[128*5];
    size_t text_size = sizeof(text_buffer);
    uint8_t config_buffer[sizeof(atecc608_config_t)];
    atecc608_config_t *config_data = (atecc608_config_t *) config_buffer;

    // initialize CryptoAuthLib for an ECC default I2C interface
    if (atcab_init(&cfg_atecc608_i2c) != ATCA_SUCCESS) {
        printf("Init error\n");
        exit(1);
    }

    // Read config data
    //  88 bytes for ATSHA devices, 128 bytes for ATECC devices and 48 bytes for Trust Anchor devices.
    if (atcab_read_config_zone(config_buffer) != ATCA_SUCCESS) {
        printf("Error reading config\n");
        exit(1);
    }

    atcab_bin2hex(config_buffer, sizeof(config_buffer), text_buffer, &text_size);

    puts("");
    puts("Current config data:");
    puts(text_buffer);
    puts("");

    int slot = 0;

    // --------------
    // Slot 00: ECC external/internal private key, ECDH output clear, regenerable
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_EXT_SIG_MASK      // External signatures of arbitrary messages are enabled.
      | ATCA_SLOT_CONFIG_INT_SIG_MASK      // Internal signatures of messages generated by GenDig or GenKey are enabled.
      | ATCA_SLOT_CONFIG_ECDH_MASK         // ECDH operation is permitted for this key.
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_GEN_KEY_MASK      // GenKey may be used to write random keys into this slot.
      ;

    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_PRIVATE_MASK       // The key slot contains an ECC private key
      | ATCA_KEY_CONFIG_PUB_INFO_MASK      // The public version of this key can always be generated.
      | ATCA_KEY_CONFIG_KEY_TYPE(4)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 01: AES key
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_ENC_READ_MASK     // Reads from this slot will be encrypted. IsSecret must also be set
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0b0111)   // Encrypted write, derive key from parent
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(6)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 02: AES key, limited uses
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_ENC_READ_MASK     // Reads from this slot will be encrypted. IsSecret must also be set
      | ATCA_SLOT_CONFIG_LIMITED_USE_MASK  // The key stored in the slot is Limited Use.
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0b0111)   // Encrypted write, derive key from parent
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(6)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;


    // --------------
    // --------------
    // Slot 03: AES key, debug
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)       // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)     // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Always read/write
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(6)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;


    // --------------
    // --------------
    // Slot 04: SHA secret
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_ENC_READ_MASK     // Reads from this slot will be encrypted. IsSecret must also be set
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0b0111)   // Encrypted write, derive key from parent
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 05: SHA secret, limited uses
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_ENC_READ_MASK     // Reads from this slot will be encrypted. IsSecret must also be set
      | ATCA_SLOT_CONFIG_LIMITED_USE_MASK  // The key stored in the slot is Limited Use.
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0b0111)   // Encrypted write, derive key from parent
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 06: SHA secret, debug
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Always read/write
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 07: SHA secret for IO key
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Clear W
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 08: Data
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Clear W
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 09: Public key of slot 00
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Clear W
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(4)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 10: SHA secret Checkmac/copy source
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(0)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_ENC_READ_MASK     // Reads from this slot will be encrypted. IsSecret must also be set
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Clear W
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 11: SHA secret Checkmac/copy target
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(0)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_ENC_READ_MASK     // Reads from this slot will be encrypted. IsSecret must also be set
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(15)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Clear W
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 12: Rolling key from Target key, debug
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0b0010)  // DeriveKey command can be run without authorizing MAC (roll).
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 13: Rolling key from Parent key, debug
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0b0011)  // DeriveKey command can be run without authorizing MAC (create).
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 14: Foreign Public key
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Clear W
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(4)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
    // --------------
    // Slot 15: SHA secret, 255 limited uses
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(7)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_LIMITED_USE_MASK  // The key stored in the slot is Limited Use.
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(7)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(0)   // Clear W
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_KEY_TYPE(7)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------


/* Slot Template

    // --------------
    // Slot: <description>
    
    // General Purpose Slot Config (Not ECC Private Keys)
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_READKEY(v)        // Use this KeyID to encrypt data read from this slot. 0 only for CheckMac/Copy
      | ATCA_SLOT_CONFIG_NOMAC_MASK        // The key stored in the slot cannot be used by the MAC or HMAC commands. 
      | ATCA_SLOT_CONFIG_LIMITED_USE_MASK  // The key stored in the slot is Limited Use.
      | ATCA_SLOT_CONFIG_ENC_READ_MASK     // Reads from this slot will be encrypted. IsSecret must also be set
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_WRITE_KEY(v)      // Use this key to validate and encrypt data written to this slot
      | ATCA_SLOT_CONFIG_WRITE_CONFIG(v)   // See Table 2-8, Table 2-9, Table 2-10, Table 2-11, and Write Command.
      ;

    // Slot Config for ECC Private Keys
    config_data->SlotConfig[slot] = 
        ATCA_SLOT_CONFIG_EXT_SIG_MASK      // External signatures of arbitrary messages are enabled.
      | ATCA_SLOT_CONFIG_INT_SIG_MASK      // Internal signatures of messages generated by GenDig or GenKey are enabled.
      | ATCA_SLOT_CONFIG_ECDH_MASK         // ECDH operation is permitted for this key.
      | ATCA_SLOT_CONFIG_WRITE_ECDH_MASK   // Master secret will be written into slot N+1. (vs. output on the clear)
      | ATCA_SLOT_CONFIG_IS_SECRET_MASK    // The contents of this slot are secret
      | ATCA_SLOT_CONFIG_GEN_KEY_MASK      // GenKey may be used to write random keys into this slot.
      | ATCA_SLOT_CONFIG_PRIV_WRITE_MASK   // Encrypted PrivWrite command allowed.
      ;

    // Key Config
    config_data->KeyConfig[slot] = 
        ATCA_KEY_CONFIG_PRIVATE_MASK       // The key slot contains an ECC private key
      | ATCA_KEY_CONFIG_PUB_INFO_MASK      // The public version of this key can always be generated.
      | ATCA_KEY_CONFIG_KEY_TYPE(v)        // 4: P256 NIST ECC key / 6: AES-256 key / 7: Not an ECC key
      | ATCA_KEY_CONFIG_LOCKABLE_MASK      // Slot can be individually locked using the Lock command.
      | ATCA_KEY_CONFIG_REQ_RANDOM_MASK    // A random nonce is required.
      | ATCA_KEY_CONFIG_REQ_AUTH_MASK      // To use this key, authorization by AuthKey must be completed
      | ATCA_KEY_CONFIG_AUTH_KEY(v)        // If ReqAuth is one, this field points to the key that must be used for authorization 
      | ATCA_KEY_CONFIG_PERSIST_DIS_MASK   // Use of this key is prohibited for all commands other than GenKey if the IntrusionLatch is zero.
      | ATCA_KEY_CONFIG_RFU_MASK           // Reserved
      | ATCA_KEY_CONFIG_X509_ID(v)         // The index into the X509format array within the configuration zone which corresponds to this slot.
      ;

    printf("[%02d]  SlotConfig: %04x   KeyConfig: %04x\n", 
        slot, 
        config_data->SlotConfig[slot], 
        config_data->KeyConfig[slot]);

    slot++;

    // --------------
*/


    config_data->SlotLocked = 0xFFFF;  // unlock all lockable slots

    atcab_bin2hex(config_buffer, sizeof(config_buffer), text_buffer, &text_size);

    puts("");
    puts("Modified config data:");
    puts(text_buffer);
    puts("");

    printf("Write configuration [y/n] ");
    ch = getchar();
    if (ch == 'y' || ch == 'Y') {
        if (status = atcab_write_config_zone (config_buffer) == ATCA_SUCCESS) {
            puts("write OK");
        }
        else {
            printf("Write Error: 0x%02x\n", status);
            exit(1);
        }
    }

    puts("Exit");

}

